# Generated by Django 3.0 on 2020-05-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='pics')),
                ('category', models.TextField()),
                ('started_from', models.DateField(verbose_name='started_from')),
            ],
        ),
    ]
